import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@tabler/core/dist/css/tabler.min.css';
import ClientWrapper from "@/components/client-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <ClientWrapper />
        {children}
      </body>
    </html>
  );
}
